### ISSUE TITLE
Recent Tracks Module

### ISSUE THREAD

**Issue by stay4you** [mastervanleeuwen/J-TrackGallery#85]
Firstly thank you for all your assistance, I am having an issue while displaying the recent tracks module as at https://www.stay4you.com/guide/tracks-routes/discover-new-paths-trails-gps-activity-map when clicking on the tracks links I get "500
Layout file not found"

()	JROOT/libraries/src/MVC/View/HtmlView.php:425
2	Joomla\CMS\MVC\View\HtmlView->loadTemplate()	JROOT/libraries/src/MVC/View/HtmlView.php:204
3	Joomla\CMS\MVC\View\HtmlView->display()	JROOT/components/com_jtg/views/files/view.html.php:212
4	JtgViewFiles->display()	JROOT/libraries/src/MVC/Controller/BaseController.php:697
5	Joomla\CMS\MVC\Controller\BaseController->display()	JROOT/components/com_jtg/controller.php:65
6	JtgController->display()	JROOT/libraries/src/MVC/Controller/BaseController.php:730
7	Joomla\CMS\MVC\Controller\BaseController->execute()	JROOT/components/com_jtg/jtg.php:90
8	require_once()	JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:71
9	Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}()	JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:73
10	Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch()	JROOT/libraries/src/Component/ComponentHelper.php:361
11	Joomla\CMS\Component\ComponentHelper::renderComponent()	JROOT/libraries/src/Application/SiteApplication.php:218
12	Joomla\CMS\Application\SiteApplication->dispatch()	JROOT/libraries/src/Application/SiteApplication.php:261
13	Joomla\CMS\Application\SiteApplication->doExecute()	JROOT/libraries/src/Application/CMSApplication.php:306
14	Joomla\CMS\Application\CMSApplication->execute()	JROOT/includes/app.php:58
15	require_once()	JROOT/index.php:32

**Comment by mastervanleeuwen** [comment]
Hi Gary,
Thanks for the report. This is now fixed in the new version here: 
https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.35-c
I think you only need to update the mod_jtrackgallery_latest , but you may want to update the full package to make sure that everything is in sync.

**Comment by stay4you** [comment]
Thanks for update, I tried full package update and module up date but still have the same issue as at https://www.stay4you.com/guide/tracks-routes/discover-new-paths-trails-gps-activity-map any ideas would be much appreciated!
Thanks Gary
